services:
  1nf1n1ty-web-frontend:
    image: t1tan/1nf1n1ty-web-frontend:latest
    restart: always
    command: "npm run start"
    env_file:
      - ./.env
    volumes:
      - type: bind
        source: ./content 
        target: /app/content
      - type: bind
        source: ./public 
        target: /app/public 
  nginx:
    build: 
      context: ./
      dockerfile: Dockerfile.nginx
    container_name: nginx-rev-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    